[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
monitor_speed = 115200
build_flags =
  -D USB_SERIAL
lib_deps =
  https://github.com/tonton81/FlexCAN_T4.git

; Add library dependencies as needed, for example:
; lib_deps =
;   tonton81/FlexCAN_T4 @ ^1.0.2
